research_task:
  description: >
    Conduct a thorough research about the company {company}. Focused on:
    1. Current company status and health
    2. Historical company performance
    3. Major challenges and opportunities
    4. Recent news and events
    5. Future outlook and potential developments

    Make sure to provide your findings in a structred and formatted way with clear sections.
    Make sure to find the latest information as posisible.
  expected_output: >
    A comprehensive financial research document with well structured sections that covers all the 
    requested aspects about the company {company}.
  agent: researcher

reporting_task:
  description: >
    Review and anlyzed the context you got from the previous task in writing the financial report
    and write a comprehensive report. Your report should include the following sections:
    1. Begin with an executive summary
    2. Include all key information from the research
    3. Provide insightful analysis of trends and patterns
    4. Offer a market outlook for company, noting that this should not be used for trading decisions
    5. Be formatted in a professional, easy-to-read style with clear headings
  expected_output: >
    A polished, professional report on {company} that presents the research
    findings with added analysis and insights. The report should be well-structured
    with an executive summary, main sections, and conclusion.
  agent: analyst
  context:
    - research_task
  output_file: output/report.md
